// Image paths for the application
export const images = {
  groupPracticeApp: './images/groupchange_application.jpg',
  question6: './images/question6.jpg',
  paytoMailto: './images/payto_mailto.jpg',
  paytoMailtoCICS: './images/payto_mailto_CICS.png',
  contactInfo: './images/contactinfo.jpg',
  emailField: './images/emailfield.png',
  practitioners: './images/practitioners.jpg',
  questions21to24: './images/21_24.jpg',
  createEnrollment: './images/CreateEnrollment.png',
  newProviderWindow: './images/newproviderwindow.png',
  groupSpecialty: './images/groupspecialty.png',
  enrollmentTab: './images/enrollmenttab.png',
  providerAddress: './images/provideraddress.png',
  mailingAddress: './images/mailingaddress.png',
  providerInfoTab: './images/providerinfotab.jpg',
  npiTab: './images/npitab.png',
  specTab: './images/spectab.png',
  claimTab: './images/claimtab.png',
  licenseDeaTab: './images/lictab.png',
  mainframe: './images/mainframe.png',
  cics: './images/CICS.png',
  addProv: './images/addprov.png',
  enrollmentTask: './images/enrollmenttask.png',
  checklist: './images/checklist.png',
  addToGroup: './images/addtogroup.png',
  letterTask: './images/lettertask.png',
  letterSelect: './images/letterselect.png',
  letterProv: './images/letterprov.png',
  generateLetter: './images/generateletter.png',
  closeLetter: './images/closeletter.png',
};
